# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import job_api_pb2 as job__api__pb2


class JobAPIStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.TrainJob = channel.stream_stream(
        '/bugrepro.JobAPI/TrainJob',
        request_serializer=job__api__pb2.TrainJobRequest.SerializeToString,
        response_deserializer=job__api__pb2.TrainJobResponse.FromString,
        )


class JobAPIServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def TrainJob(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_JobAPIServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'TrainJob': grpc.stream_stream_rpc_method_handler(
          servicer.TrainJob,
          request_deserializer=job__api__pb2.TrainJobRequest.FromString,
          response_serializer=job__api__pb2.TrainJobResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'bugrepro.JobAPI', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
