# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: job_api.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='job_api.proto',
  package='bugrepro',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\rjob_api.proto\x12\x08\x62ugrepro\"\x11\n\x0fTrainJobRequest\"\x12\n\x10TrainJobResponse2O\n\x06JobAPI\x12\x45\n\x08TrainJob\x12\x19.bugrepro.TrainJobRequest\x1a\x1a.bugrepro.TrainJobResponse(\x01\x30\x01\x62\x06proto3'
)




_TRAINJOBREQUEST = _descriptor.Descriptor(
  name='TrainJobRequest',
  full_name='bugrepro.TrainJobRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=44,
)


_TRAINJOBRESPONSE = _descriptor.Descriptor(
  name='TrainJobResponse',
  full_name='bugrepro.TrainJobResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=64,
)

DESCRIPTOR.message_types_by_name['TrainJobRequest'] = _TRAINJOBREQUEST
DESCRIPTOR.message_types_by_name['TrainJobResponse'] = _TRAINJOBRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TrainJobRequest = _reflection.GeneratedProtocolMessageType('TrainJobRequest', (_message.Message,), {
  'DESCRIPTOR' : _TRAINJOBREQUEST,
  '__module__' : 'job_api_pb2'
  # @@protoc_insertion_point(class_scope:bugrepro.TrainJobRequest)
  })
_sym_db.RegisterMessage(TrainJobRequest)

TrainJobResponse = _reflection.GeneratedProtocolMessageType('TrainJobResponse', (_message.Message,), {
  'DESCRIPTOR' : _TRAINJOBRESPONSE,
  '__module__' : 'job_api_pb2'
  # @@protoc_insertion_point(class_scope:bugrepro.TrainJobResponse)
  })
_sym_db.RegisterMessage(TrainJobResponse)



_JOBAPI = _descriptor.ServiceDescriptor(
  name='JobAPI',
  full_name='bugrepro.JobAPI',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=66,
  serialized_end=145,
  methods=[
  _descriptor.MethodDescriptor(
    name='TrainJob',
    full_name='bugrepro.JobAPI.TrainJob',
    index=0,
    containing_service=None,
    input_type=_TRAINJOBREQUEST,
    output_type=_TRAINJOBRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_JOBAPI)

DESCRIPTOR.services_by_name['JobAPI'] = _JOBAPI

# @@protoc_insertion_point(module_scope)
